// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbB5ZlieEyPAKGPa-TEkz_CEPlKLFmn54',
    appId: '1:668853374217:web:c8c68c010a164e641b17d8',
    messagingSenderId: '668853374217',
    projectId: 'present-948c7',
    authDomain: 'present-948c7.firebaseapp.com',
    storageBucket: 'present-948c7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6D0r6O2Fu_lVoGWQu4-Uetc8l2tAU9Tc',
    appId: '1:668853374217:android:712e205b1de969981b17d8',
    messagingSenderId: '668853374217',
    projectId: 'present-948c7',
    storageBucket: 'present-948c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwCJoO1hin_v8k5lESQaVd4pgKzzAkU3E',
    appId: '1:668853374217:ios:275356eff1a9bee71b17d8',
    messagingSenderId: '668853374217',
    projectId: 'present-948c7',
    storageBucket: 'present-948c7.appspot.com',
    iosBundleId: 'gr.techzombie.present',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwCJoO1hin_v8k5lESQaVd4pgKzzAkU3E',
    appId: '1:668853374217:ios:275356eff1a9bee71b17d8',
    messagingSenderId: '668853374217',
    projectId: 'present-948c7',
    storageBucket: 'present-948c7.appspot.com',
    iosBundleId: 'gr.techzombie.present',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbB5ZlieEyPAKGPa-TEkz_CEPlKLFmn54',
    appId: '1:668853374217:web:29d2e4120e06f67a1b17d8',
    messagingSenderId: '668853374217',
    projectId: 'present-948c7',
    authDomain: 'present-948c7.firebaseapp.com',
    storageBucket: 'present-948c7.appspot.com',
  );
}
